apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
spec:
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
        - name: community
          image: 20221174/yorijori_community:4.7 # 4.7은 passport 설정 한 것
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: yorijori_community # 나중에 전용 데이터베이스로 변경 예정
            - name: DB_USER
              value: root
            - name: DB_PW
              value: root
            - name: DOMAIN_NAME
              value: http://yorijori.com
            - name: PORT
              value: "3000"
            - name: SEARCH_SERVICE
              value: "search"
            - name: SEARCH_SERVICE_PORT
              value: "3000"
            - name: IMAGE_SERVICE
              value: "image"
            - name: SEARCH_SERVICE_PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: community
spec:
  selector:
    app: community
  ports:
    - port: 3000
      targetPort: 3000
